export const DESTINATIONS_DETAILS = [
  {
    id:1,
    hImage: '/images/destination-1.jpg',
    hName: 'Enjoy the Beauty of the Rialto Bridge',
    hPlace: 'Venezia, Italy',
    hStar: 4.5,
    hReview: '1.8k',
  },
  {
    id:2,
    hImage: '/images/destination-2.jpg',
    hName: 'Enjoy the Beauty of the Floating City',
    hPlace: 'Skye, Skotlandia',
    hStar: 4.7,
    hReview: '1.2k',
  },
  {
    id:3,
    hImage: '/images/destination-3.jpg',
    hName: 'Enjoy the Beauty of the Brazil City',
    hPlace: 'Rio de Janeiro, Brazil',
    hStar: 4.1,
    hReview: '1.1k',
  },
  {
    id:4,
    hImage: '/images/destination-4.jpg',
    hName: 'Enjoy the Beauty of the Rialto Bridge',
    hPlace: 'Venezia, Italy',
    hStar: 3.9,
    hReview: '1.0k',
  },
  {
    id:5,
    hImage: '/images/destination-5.jpg',
    hName: 'Enjoy the Beauty of the Floating City',
    hPlace: 'Skye, Skotlandia',
    hStar: 3.9,
    hReview: '1.0k',
  },
  {
    id:6,
    hImage: '/images/destination-6.jpg',
    hName: 'Enjoy the Beauty of the Brazil City',
    hPlace: 'Rio de Janeiro, Brazil',
    hStar: 4.2,
    hReview: '1.2k',
  },
]
